# **SQL Basics for AI - Subjective**
### **Problem Statement**
* You are a data analyst at a tech company. The HR department needs insights about employee data. You have access to an employees table with the following structure:

### Employees Table

| Column        | Data Type | Description                          |
|---------------|-----------|--------------------------------------|
| employee_id   | INTEGER   | Unique identifier (Primary Key)      |
| name          | TEXT      | Employee name                        |
| department    | TEXT      | Department name                      |
| salary        | INTEGER   | Annual salary                        |
| hire_date     | DATE      | Date of joining                      |

The table contains 100 employee records across departments: Engineering, Sales, Marketing, Finance, HR, and Operations.

In [27]:
import sqlite3
conn = sqlite3.connect("Employee.db")
cursor = conn.cursor()
print("Employee Database created Successfully")

Employee Database created Successfully

In [28]:
cursor.execute ("""
            create table employees (employee_id int primary key ,
                                    emp_name text ,
                                    department text ,
                                    salary int ,
                                    hire_date date);
                  """)

conn.commit()

* I created a new SQLite database called Employee.db.
* Inside it, we created a table called employees with columns for ID, name, department, salary, and joining date.
* employee_id is unique for each employee.

In [14]:
!pip install faker

Collecting faker
  Downloading faker-40.11.0-py3-none-any.whl.metadata (16 kB)
Downloading faker-40.11.0-py3-none-any.whl (2.0 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.0/2.0 MB 24.1 MB/s eta 0:00:00
Installing collected packages: faker
Successfully installed faker-40.11.0

In [29]:
# The table contains 100 employee records across departments: Engineering, Sales, Marketing, Finance, HR, and Operations.
# insert employees record
from faker import Faker
import random
from datetime import datetime, timedelta

fake = Faker()
departments = ["Engineering", "Sales", "Marketing", "Finance", "HR", "Operations"]
for i in range(1,101):
    name = fake.name()
    dept = random.choice(departments)
    salary = random.randint(40000,120000)
    hire_date = fake.date_between(start_date='-5y', end_date='today').strftime("%Y-%m-%d")  # convert to string

    cursor.execute("""
    INSERT INTO employees VALUES (?, ?, ?, ?, ?)
    """,(i,name,dept,salary,hire_date))

conn.commit()

* I installed Faker, a Python tool to generate realistic fake data.

* Generated 100 employees with random names, departments, salaries, and hire dates.

* Each employee is added to the database with a unique ID.

In [31]:
import pandas as pd
emp_df = pd.read_sql_query("Select * from employees",conn)
emp_df.head(10)

   employee_id           emp_name   department  salary   hire_date
0            1      Miguel Morris   Operations   99253  2022-08-16
1            2         Amy Haynes  Engineering   41141  2021-07-31
2            3     Rebecca Dalton           HR   65847  2024-11-09
3            4      Jeremy Bailey    Marketing  101952  2021-07-25
4            5  Jacqueline Austin    Marketing  109887  2021-06-13
5            6  Courtney Franklin      Finance   97262  2021-11-25
6            7       Jordan Allen        Sales  113265  2022-03-29
7            8      Laura Murillo      Finance   65388  2025-07-04
8            9    Reginald Mosley        Sales   88360  2021-06-07
9           10    James Holmes MD   Operations   60405  2024-02-11

* I loaded the employees table into a Pandas DataFrame to view it easily.

* **emp_df.head(10)** shows the first 10 employees for a quick check.

# Task 1: Basic Querying

In [32]:
# Write SQL queries to answer the following:
# 1. Select all columns for employees in the Marketing department
marketing_dept = pd.read_sql_query("select * from employees where department = 'Marketing' ",conn)
marketing_dept

    employee_id           emp_name department  salary   hire_date
0             4      Jeremy Bailey  Marketing  101952  2021-07-25
1             5  Jacqueline Austin  Marketing  109887  2021-06-13
2            27     Jason Mckinney  Marketing  112801  2023-12-11
3            28    Felicia Hampton  Marketing   95713  2023-09-24
4            34     Elizabeth Cruz  Marketing   63880  2023-11-29
5            39  Robert Martin DDS  Marketing  117806  2025-03-09
6            40     Michael Bright  Marketing   41551  2024-04-25
7            42      Matthew Rivas  Marketing   96865  2023-01-02
8            45      Jeffrey Smith  Marketing   73513  2025-05-07
9            49      Teresa Holmes  Marketing   95900  2024-09-12
10           85      Kyle Mcdonald  Marketing   66652  2024-09-30
11           87    Stephen Baldwin  Marketing   64493  2026-02-02
12           88        Randy Dixon  Marketing  109370  2022-03-24
13           91        Ruth Martin  Marketing   75979  2024-02-07
14           92       Cody Johnson  Marketing   68509  2021-09-14

* Shows all employee details who work in Marketing.
* Helps HR quickly find everyone in that department.

In [37]:
# 2. Display only name, department, and salary for employees earning more than $90,000
high_salary = pd.read_sql_query("select emp_name ,department,salary from employees where salary > 90000 order by salary DESC ", conn)
high_salary

              emp_name   department  salary
0      Jeremy Richmond        Sales  119663
1    Robert Martin DDS    Marketing  117806
2        Jennifer Byrd           HR  116854
3         Justin Boone      Finance  115469
4    Raven Christensen        Sales  115250
5         Casey Murphy      Finance  113882
6         Jordan Allen        Sales  113265
7       Jason Mckinney    Marketing  112801
8          Eric Pruitt  Engineering  112407
9      Michael Griffin           HR  112054
10      Brian Williams        Sales  110943
11          Kelsey Day        Sales  110885
12        Kathy Fowler      Finance  110466
13   Jacqueline Austin    Marketing  109887
14         Randy Dixon    Marketing  109370
15         Manuel Shaw      Finance  109184
16    Cheryl Myers DDS   Operations  108419
17        Michael Ryan  Engineering  106689
18       Dennis Rangel           HR  106328
19         Susan Myers  Engineering  105925
20     Timothy Vazquez           HR  105403
21         Scott Klein        Sales  104754
22  Kimberly Alexander      Finance  104521
23    Elizabeth Romero  Engineering  103920
24         Miranda Ray        Sales  103454
25     Austin Morrison      Finance  102607
26       Jeremy Bailey    Marketing  101952
27        Destiny Hess           HR   99289
28       Miguel Morris   Operations   99253
29          Ryan Meyer   Operations   97937
30   Courtney Franklin      Finance   97262
31       Matthew Rivas    Marketing   96865
32        Henry Nguyen        Sales   96176
33       Teresa Holmes    Marketing   95900
34     Felicia Hampton    Marketing   95713
35           Eric Cole           HR   93633
36       Philip Newton        Sales   91190

* Shows only name, department, and salary for employees earning above 90000.
* Sorted from highest to lowest salary to easily see top earners.

In [38]:
# 3. Find employees in either Sales OR Finance departments
sal_fin_dept = pd.read_sql_query("select * from employees where department = 'Sales'  OR department = 'Finance'",conn)
sal_fin_dept

    employee_id              emp_name department  salary   hire_date
0             6     Courtney Franklin    Finance   97262  2021-11-25
1             7          Jordan Allen      Sales  113265  2022-03-29
2             8         Laura Murillo    Finance   65388  2025-07-04
3             9       Reginald Mosley      Sales   88360  2021-06-07
4            13        Vincent Castro    Finance   84389  2022-02-11
5            15         William Green      Sales   58722  2026-02-02
6            17       Jeremy Richmond      Sales  119663  2023-05-07
7            21         Monique Perry      Sales   42588  2022-12-19
8            22         Shari Rollins    Finance   47994  2023-04-04
9            23          Kathy Fowler    Finance  110466  2021-09-24
10           25       Austin Morrison    Finance  102607  2022-11-25
11           36        Teresa Mcclure      Sales   53584  2026-01-25
12           37  Nicholas Burgess PhD    Finance   61934  2023-06-12
13           38       Michelle Garcia      Sales   55497  2025-07-23
14           41        Julie Sullivan    Finance   60662  2021-04-15
15           43             Amy Gross    Finance   47934  2023-09-04
16           46           Manuel Shaw    Finance  109184  2024-12-15
17           47   Dennis Williams PhD    Finance   53303  2022-11-08
18           48           Gary Massey      Sales   48768  2023-02-11
19           51            Sean Lynch    Finance   42201  2022-09-28
20           52         Mallory Smith      Sales   41430  2025-02-08
21           53          Richard Rowe    Finance   83306  2022-08-30
22           57            Kelsey Day      Sales  110885  2022-07-10
23           60          Rachael Ford      Sales   84967  2021-04-09
24           61           Steven Moon    Finance   86200  2024-05-08
25           62        Tracy Lawrence    Finance   77714  2023-12-24
26           63          Erica Norton    Finance   77058  2026-02-23
27           66        Brandon Krause    Finance   52443  2021-10-09
28           67          Regina Allen      Sales   52523  2024-06-11
29           68     Elizabeth Johnson    Finance   47926  2026-01-26
30           69        Sabrina Warren    Finance   47799  2022-02-10
31           71          Kristy Downs    Finance   67975  2023-09-15
32           73          Casey Murphy    Finance  113882  2023-04-15
33           74         Philip Newton      Sales   91190  2021-12-17
34           75           Scott Klein      Sales  104754  2022-10-11
35           76          Henry Nguyen      Sales   96176  2022-04-11
36           77           Robert Carr      Sales   70859  2024-12-25
37           79           Miranda Ray      Sales  103454  2023-08-31
38           81    Kimberly Alexander    Finance  104521  2024-02-15
39           84        Nicholas James    Finance   84527  2025-04-11
40           86      Christian Becker    Finance   51567  2022-05-06
41           89     Raven Christensen      Sales  115250  2025-02-23
42           94          Justin Boone    Finance  115469  2025-11-23
43           95    Nicholas Hernandez    Finance   52299  2026-01-15
44           98           Maria Boone      Sales   50311  2021-04-11
45           99        Brian Williams      Sales  110943  2024-04-24
46          100           John Ortega      Sales   85225  2022-05-20

* Shows all details for employees in Sales or Finance.
* Using IN makes it simpler than multiple OR conditions.

# Task 2: Sorting and Limiting

In [39]:
# Write SQL queries to find:
# 1. The top 5 highest-paid employees (sort by salary descending, limit to 5)
top_emp = pd.read_sql_query("select * from employees order by salary DESC limit 5",conn)
top_emp

   employee_id           emp_name department  salary   hire_date
0           17    Jeremy Richmond      Sales  119663  2023-05-07
1           39  Robert Martin DDS  Marketing  117806  2025-03-09
2           72      Jennifer Byrd         HR  116854  2021-03-15
3           94       Justin Boone    Finance  115469  2025-11-23
4           89  Raven Christensen      Sales  115250  2025-02-23

* Finds the top 5 employees with the highest salaries.

* Useful for spotting top performers or budgeting for raises.

In [42]:
# 2. The 3 most recently hired employees in Engineering department (sort by hire_date descending)
most_engg_dept = pd.read_sql_query("select * from employees where department = 'Engineering' order by hire_date DESC limit 3",conn)
most_engg_dept

   employee_id          emp_name   department  salary   hire_date
0           14  Elizabeth Romero  Engineering  103920  2026-02-18
1           24      Amanda Perry  Engineering   78652  2025-02-28
2           16       Eric Pruitt  Engineering  112407  2024-07-04

* Shows the latest 3 employees who joined Engineering.

* Helps HR track recent hiring trends.

In [43]:
# 3.The oldest employee (by hire_date) who earns more than $70,000 and is NOT in HR department
old_emp = pd.read_sql_query("select * from employees where salary > 70000 and department NOT in ('Engineering') order by hire_date  ",conn)
old_emp

    employee_id            emp_name  department  salary   hire_date
0            72       Jennifer Byrd          HR  116854  2021-03-15
1            60        Rachael Ford       Sales   84967  2021-04-09
2             9     Reginald Mosley       Sales   88360  2021-06-07
3             5   Jacqueline Austin   Marketing  109887  2021-06-13
4             4       Jeremy Bailey   Marketing  101952  2021-07-25
5            23        Kathy Fowler     Finance  110466  2021-09-24
6             6   Courtney Franklin     Finance   97262  2021-11-25
7            90          Ryan Meyer  Operations   97937  2021-12-12
8            74       Philip Newton       Sales   91190  2021-12-17
9            13      Vincent Castro     Finance   84389  2022-02-11
10           88         Randy Dixon   Marketing  109370  2022-03-24
11            7        Jordan Allen       Sales  113265  2022-03-29
12           76        Henry Nguyen       Sales   96176  2022-04-11
13           44        Destiny Hess          HR   99289  2022-05-03
14          100         John Ortega       Sales   85225  2022-05-20
15           57          Kelsey Day       Sales  110885  2022-07-10
16            1       Miguel Morris  Operations   99253  2022-08-16
17           53        Richard Rowe     Finance   83306  2022-08-30
18           75         Scott Klein       Sales  104754  2022-10-11
19           96     Michael Griffin          HR  112054  2022-10-11
20           25     Austin Morrison     Finance  102607  2022-11-25
21           42       Matthew Rivas   Marketing   96865  2023-01-02
22           83        Kelsey Velez          HR   78014  2023-02-15
23           73        Casey Murphy     Finance  113882  2023-04-15
24           17     Jeremy Richmond       Sales  119663  2023-05-07
25           30     Timothy Vazquez          HR  105403  2023-06-12
26           19    Katelyn Gonzalez  Operations   88407  2023-08-25
27           79         Miranda Ray       Sales  103454  2023-08-31
28           28     Felicia Hampton   Marketing   95713  2023-09-24
29           58       Dennis Rangel          HR  106328  2023-11-11
30           27      Jason Mckinney   Marketing  112801  2023-12-11
31           62      Tracy Lawrence     Finance   77714  2023-12-24
32           91         Ruth Martin   Marketing   75979  2024-02-07
33           81  Kimberly Alexander     Finance  104521  2024-02-15
34           99      Brian Williams       Sales  110943  2024-04-24
35           61         Steven Moon     Finance   86200  2024-05-08
36           59    Cheryl Myers DDS  Operations  108419  2024-06-09
37           64           Eric Cole          HR   93633  2024-08-01
38           49       Teresa Holmes   Marketing   95900  2024-09-12
39           46         Manuel Shaw     Finance  109184  2024-12-15
40           77         Robert Carr       Sales   70859  2024-12-25
41           26         Tara Carson          HR   84746  2025-02-01
42           89   Raven Christensen       Sales  115250  2025-02-23
43           56     Michael Jackson  Operations   85413  2025-03-01
44           39   Robert Martin DDS   Marketing  117806  2025-03-09
45           84      Nicholas James     Finance   84527  2025-04-11
46           45       Jeffrey Smith   Marketing   73513  2025-05-07
47           35      Charles Willis          HR   74733  2025-10-31
48           94        Justin Boone     Finance  115469  2025-11-23
49           63        Erica Norton     Finance   77058  2026-02-23

* Finds the longest-serving employee earning more than 70000 but not in HR.
* Useful for reward programs or mentoring plans.

# Task 3: Calculated Fields and Aliases

In [46]:
# 1. Calculate monthly salary for all employees:
#  Display name, salary, and salary/12 aliased as monthly_pay
month_salary = pd.read_sql_query("select emp_name as Name ,salary as Annual_pay , salary/12 as Monthly_pay from employees",conn)
month_salary

                 Name  Annual_pay  Monthly_pay
0       Miguel Morris       99253         8271
1          Amy Haynes       41141         3428
2      Rebecca Dalton       65847         5487
3       Jeremy Bailey      101952         8496
4   Jacqueline Austin      109887         9157
..                ...         ...          ...
95    Michael Griffin      112054         9337
96    Melissa Stewart       41846         3487
97        Maria Boone       50311         4192
98     Brian Williams      110943         9245
99        John Ortega       85225         7102

[100 rows x 3 columns]

* Calculates monthly salary by dividing annual salary by 12.
*  Shows name, annual pay, and monthly pay for all employees.

In [47]:
#  Only show employees earning more than $60,000
earn_more_salary = pd.read_sql_query("select emp_name as Name ,salary as Annual_pay , salary/12 as Monthly_pay from employees where salary >60000",conn)
earn_more_salary

                 Name  Annual_pay  Monthly_pay
0       Miguel Morris       99253         8271
1      Rebecca Dalton       65847         5487
2       Jeremy Bailey      101952         8496
3   Jacqueline Austin      109887         9157
4   Courtney Franklin       97262         8105
..                ...         ...          ...
67       Michael Ryan      106689         8890
68       Justin Boone      115469         9622
69    Michael Griffin      112054         9337
70     Brian Williams      110943         9245
71        John Ortega       85225         7102

[72 rows x 3 columns]

* Same as above but only for employees earning more than 60000.
* Helps HR focus on higher-earning employees for financial planning.

In [49]:
# 2. Create a report for the Finance department showing:
# name aliased as employee_name # salary aliased as annual_salary
# salary/12 aliased as monthly_salary # Sort by salary descending
salary_Report= pd.read_sql_query("select emp_name as employee_Name ,salary as Annual_Salary , salary/12 as Monthly_Salary from  employees WHERE department = 'Finance' order by salary DESC",conn)
salary_Report

           employee_Name  Annual_Salary  Monthly_Salary
0           Justin Boone         115469            9622
1           Casey Murphy         113882            9490
2           Kathy Fowler         110466            9205
3            Manuel Shaw         109184            9098
4     Kimberly Alexander         104521            8710
5        Austin Morrison         102607            8550
6      Courtney Franklin          97262            8105
7            Steven Moon          86200            7183
8         Nicholas James          84527            7043
9         Vincent Castro          84389            7032
10          Richard Rowe          83306            6942
11        Tracy Lawrence          77714            6476
12          Erica Norton          77058            6421
13          Kristy Downs          67975            5664
14         Laura Murillo          65388            5449
15  Nicholas Burgess PhD          61934            5161
16        Julie Sullivan          60662            5055
17   Dennis Williams PhD          53303            4441
18        Brandon Krause          52443            4370
19    Nicholas Hernandez          52299            4358
20      Christian Becker          51567            4297
21         Shari Rollins          47994            3999
22             Amy Gross          47934            3994
23     Elizabeth Johnson          47926            3993
24        Sabrina Warren          47799            3983
25            Sean Lynch          42201            3516

* Reports Finance employees with annual & monthly salaries, sorted high → low.
* Useful for budgeting, salary review, or departmental analysis.

# Conclusion :
In this Assignment, I looked at our employee data to help HR understand the team better. I found who works in which department, who earns the most, and who joined recently or has been with the company the longest. I also calculated monthly salaries and created clear reports for departments like Finance.

Overall, these queries make it easy to see patterns, make decisions, and plan for salaries, promotions, or hiring. It shows how SQL can turn raw employee data into useful insights for the company.